# Generated by Django 4.2.1 on 2023-06-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sauce_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taco',
            name='sauces',
            field=models.ManyToManyField(to='main_app.sauce'),
        ),
    ]
